# Generated by Django 4.1.6 on 2023-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_alter_card_parentnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='parentnode',
            field=models.CharField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
