# Generated by Django 4.1.6 on 2023-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_card_xcoordinate_card_ycoordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='xcoordinate',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ycoordinate',
        ),
        migrations.AddField(
            model_name='card',
            name='parentnode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
