# Generated by Django 4.1.6 on 2023-03-07 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0015_alter_card_cardtype_alter_card_title'),
        ('card_interactions', '0006_alter_comment_comment_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='Resource',
        ),
    ]
