# Generated by Django 4.1.6 on 2023-04-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_interactions', '0008_remove_follower_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='document_url',
            field=models.URLField(),
        ),
    ]
