# Generated by Django 4.1.6 on 2023-04-11 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0033_alter_card_author_alter_card_workshop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card_interactions', '0010_alter_comment_author_alter_resource_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_card', to='workshop.card'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='card_liked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_card', to='workshop.card'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_card', to='workshop.card'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
