# Generated by Django 4.1.6 on 2023-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_interactions', '0011_alter_comment_author_alter_comment_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='media/avatars/')),
            ],
        ),
    ]
