# Generated by Django 4.1.6 on 2023-04-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_interactions', '0012_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmodel',
        ),
    ]
