# Generated by Django 4.1.6 on 2023-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_card_description_alter_card_title_and_more'),
        ('users', '0005_alter_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('none'), to='workshop.workshop'),
        ),
    ]
