# Generated by Django 4.1.7 on 2023-04-28 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('workshop_name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('workshop_date', models.DateTimeField()),
                ('card_order', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(related_name='workshop_participants', to=settings.AUTH_USER_MODEL)),
                ('workshop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cardtype', models.CharField(choices=[('legend_1', 'Legend 1'), ('legend_2', 'Legend 2'), ('legend_3', 'Legend 3'), ('legend_4', 'Legend 4'), ('legend_5', 'Legend 5'), ('image_card', 'Image Card'), ('empty', 'Empty')], max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_Url', models.URLField(blank=True, default='https://www.grouphealth.ca/wp-content/uploads/2018/05/placeholder-image.png')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='media/cardimages/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_author', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='card_followers', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='workshop.workshop')),
            ],
        ),
    ]
