# Generated by Django 4.1.6 on 2023-05-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_card_title_importimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_Url',
        ),
        migrations.AddField(
            model_name='card',
            name='image_thumbnail',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/cardimages/'),
        ),
        migrations.AlterField(
            model_name='importimages',
            name='zip_import',
            field=models.FileField(blank=True, upload_to='media/temporary/'),
        ),
    ]
