# Generated by Django 4.1.6 on 2023-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_card_description_alter_card_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='xcoordinate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ycoordinate',
            field=models.TextField(blank=True),
        ),
    ]
