# Generated by Django 4.1.6 on 2023-05-06 11:54

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_remove_card_image_url_card_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image_thumbnail',
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=thumbnails.fields.ImageField(blank=True, default=None, null=True, upload_to='media/cardimages/'),
        ),
        migrations.DeleteModel(
            name='ImportImages',
        ),
    ]
