# Generated by Django 4.1.6 on 2023-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_card_parentnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(default='0-5', max_length=10),
        ),
    ]
