# Generated by Django 4.1.6 on 2023-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_card_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='location',
        ),
        migrations.AddField(
            model_name='card',
            name='x_location',
            field=models.CharField(default='16', max_length=5),
        ),
        migrations.AddField(
            model_name='card',
            name='y_location',
            field=models.CharField(default='5', max_length=5),
        ),
    ]
