# Generated by Django 4.1.6 on 2023-03-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_remove_card_location_card_x_location_card_y_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.CharField(choices=[('ambition', 'Ambition'), ('challenge', 'Challenge'), ('idea', 'Idea'), ('pro', 'Pro'), ('con', 'Con'), ('add', 'Add'), ('remove', 'Remove')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='x_location',
            field=models.CharField(default='13', max_length=5),
        ),
    ]
