# Generated by Django 4.1.6 on 2023-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_alter_card_cardtype_alter_card_x_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='x_location',
        ),
        migrations.RemoveField(
            model_name='card',
            name='y_location',
        ),
        migrations.AddField(
            model_name='workshop',
            name='card_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
