# Generated by Django 4.1.6 on 2023-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_remove_card_x_location_remove_card_y_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='parentnode',
        ),
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.CharField(choices=[('ambition', 'Ambition'), ('challenge', 'Challenge'), ('idea', 'Idea'), ('pro', 'Pro'), ('con', 'Con'), ('add', 'Add'), ('remove', 'Remove'), ('empty', 'Empty')], max_length=20),
        ),
    ]
