# Generated by Django 4.1.6 on 2023-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_remove_card_parentnode_alter_card_cardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.CharField(choices=[('ambition', 'Ambition'), ('challenge', 'Challenge'), ('idea', 'Idea'), ('pro', 'Pro'), ('con', 'Con'), ('empty', 'Empty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
