# Generated by Django 4.1.6 on 2023-03-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_alter_card_cardtype_alter_card_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_label', models.CharField(max_length=40)),
                ('legend_icon', models.CharField(max_length=40)),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshoplegenda', to='workshop.workshop')),
            ],
        ),
    ]
