# Generated by Django 4.1.6 on 2023-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='legenda',
            name='legend_color',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
