# Generated by Django 4.1.6 on 2023-04-05 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_alter_workshop_workshop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legenda',
            old_name='legend_color',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='legenda',
            old_name='legend_icon',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='legenda',
            name='legend_label',
        ),
        migrations.RemoveField(
            model_name='legenda',
            name='workshop',
        ),
        migrations.AddField(
            model_name='legenda',
            name='hexcolor',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legend_1', to='workshop.legenda'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legend_2', to='workshop.legenda'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legend_3', to='workshop.legenda'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legend_4', to='workshop.legenda'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legend_5', to='workshop.legenda'),
        ),
    ]
