# Generated by Django 4.1.6 on 2023-04-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_legenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legenda',
            name='legend_color',
        ),
        migrations.RemoveField(
            model_name='legenda',
            name='legend_icon',
        ),
        migrations.RemoveField(
            model_name='legenda',
            name='legend_label',
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_hex_color_1',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_hex_color_2',
            field=models.CharField(default='51c1ff', max_length=6),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_hex_color_3',
            field=models.CharField(default='51c1ff', max_length=6),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_hex_color_4',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_hex_color_5',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_icon_1',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_icon_2',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_icon_3',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_icon_4',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_icon_5',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_label_1',
            field=models.CharField(default='Con', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_label_2',
            field=models.CharField(default='Idea', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_label_3',
            field=models.CharField(default='Pro', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_label_4',
            field=models.CharField(default='Challenge', max_length=40),
        ),
        migrations.AddField(
            model_name='legenda',
            name='legend_label_5',
            field=models.CharField(default='Ambition', max_length=40),
        ),
        migrations.AlterField(
            model_name='legenda',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshoplegend', to='workshop.workshop'),
        ),
    ]
