# Generated by Django 4.1.6 on 2023-04-05 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0023_remove_legenda_workshop_workshop_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='legend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshoplegend', to='workshop.legenda'),
        ),
    ]
