# Generated by Django 4.1.6 on 2023-04-05 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0026_alter_workshop_legend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='legend',
        ),
        migrations.AddField(
            model_name='legenda',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='legenda',
            name='workshop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legend', to='workshop.workshop'),
        ),
    ]
