# Generated by Django 4.1.6 on 2023-04-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0027_remove_workshop_legend_legenda_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='legend_hex_color_1',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_hex_color_2',
            field=models.CharField(default='51c1ff', max_length=6),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_hex_color_3',
            field=models.CharField(default='51c1ff', max_length=6),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_hex_color_4',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_hex_color_5',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_icon_1',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_icon_2',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_icon_3',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_icon_4',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_icon_5',
            field=models.CharField(default='thumbs-up-solid.svg', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_label_1',
            field=models.CharField(default='Con', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_label_2',
            field=models.CharField(default='Idea', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_label_3',
            field=models.CharField(default='Pro', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_label_4',
            field=models.CharField(default='Challenge', max_length=40),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legend_label_5',
            field=models.CharField(default='Ambition', max_length=40),
        ),
    ]
