# Generated by Django 4.1.6 on 2023-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0028_workshop_legend_hex_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.CharField(choices=[('legend_1', 'Legend 1'), ('challenge', 'Challenge'), ('idea', 'Idea'), ('pro', 'Pro'), ('con', 'Con'), ('empty', 'Empty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legenda',
            name='legend_label_5',
            field=models.CharField(default='legend_1', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_5',
            field=models.CharField(default='legend_1', max_length=40),
        ),
    ]
