# Generated by Django 4.1.6 on 2023-04-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0030_alter_card_cardtype_alter_legenda_legend_label_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_Url',
            field=models.URLField(blank=True),
        ),
    ]
