# Generated by Django 4.1.6 on 2023-04-11 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0032_alter_card_author_alter_workshop_workshop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='workshop.workshop'),
        ),
        migrations.AlterField(
            model_name='legenda',
            name='workshop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend', to='workshop.workshop'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
