# Generated by Django 4.1.6 on 2023-04-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0028_workshop_legend_hex_color_1_and_more 2'),
        ('workshop', '0029_alter_card_cardtype_alter_legenda_legend_label_5_and_more 2'),
        ('workshop', '0030_alter_card_cardtype_alter_legenda_legend_label_1_and_more 2'),
        ('workshop', '0033_alter_card_author_alter_card_workshop_and_more'),
    ]

    operations = [
    ]
