# Generated by Django 4.1.6 on 2023-04-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0034_merge_20230411_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.CharField(choices=[('legend_1', 'Legend 1'), ('legend_2', 'Legend 2'), ('legend_3', 'Legend 3'), ('legend_4', 'Legend 4'), ('legend_5', 'Legend 5'), ('image_card', 'Image Card'), ('empty', 'Empty')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_1',
            field=models.CharField(default='legend_5', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_2',
            field=models.CharField(default='legend_3', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_4',
            field=models.CharField(default='legend_2', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_5',
            field=models.CharField(default='legend_1', max_length=40),
        ),
    ]
