# Generated by Django 4.1.6 on 2023-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0035_alter_card_cardtype_alter_workshop_legend_label_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='legend_hex_color_1',
            field=models.CharField(default='78E7BF', max_length=6),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_hex_color_3',
            field=models.CharField(default='ffeb39', max_length=6),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_hex_color_4',
            field=models.CharField(default='E6799D', max_length=6),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_hex_color_5',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_1',
            field=models.CharField(default='legend_1', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_2',
            field=models.CharField(default='legend_2', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_3',
            field=models.CharField(default='legend_3', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_4',
            field=models.CharField(default='legend_4', max_length=40),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='legend_label_5',
            field=models.CharField(default='legend_5', max_length=40),
        ),
    ]
