# Generated by Django 4.1.6 on 2023-04-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0036_alter_workshop_legend_hex_color_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Legenda',
        ),
    ]
