# Generated by Django 4.1.6 on 2023-04-11 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0037_delete_legenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_label_1', models.CharField(default='legend_5', max_length=40)),
                ('legend_hex_color_1', models.CharField(default='ffeb39', max_length=6)),
                ('legend_icon_1', models.CharField(default='thumbs-up-solid.svg', max_length=40)),
                ('legend_label_2', models.CharField(default='legend_3', max_length=40)),
                ('legend_hex_color_2', models.CharField(default='51c1ff', max_length=6)),
                ('legend_icon_2', models.CharField(default='thumbs-up-solid.svg', max_length=40)),
                ('legend_label_3', models.CharField(default='Pro', max_length=40)),
                ('legend_hex_color_3', models.CharField(default='51c1ff', max_length=6)),
                ('legend_icon_3', models.CharField(default='thumbs-up-solid.svg', max_length=40)),
                ('legend_label_4', models.CharField(default='legend_2', max_length=40)),
                ('legend_hex_color_4', models.CharField(default='ffeb39', max_length=6)),
                ('legend_icon_4', models.CharField(default='thumbs-up-solid.svg', max_length=40)),
                ('legend_label_5', models.CharField(default='legend_1', max_length=40)),
                ('legend_hex_color_5', models.CharField(default='ffeb39', max_length=6)),
                ('legend_icon_5', models.CharField(default='thumbs-up-solid.svg', max_length=40)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('workshop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend', to='workshop.workshop')),
            ],
        ),
    ]
