# Generated by Django 4.1.6 on 2023-04-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0039_alter_card_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Legenda',
        ),
    ]
