# Generated by Django 4.1.6 on 2023-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0040_delete_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_Url',
            field=models.URLField(blank=True, default='https://www.grouphealth.ca/wp-content/uploads/2018/05/placeholder-image.png'),
        ),
    ]
