# Generated by Django 4.1.6 on 2023-04-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0041_alter_card_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
