# Generated by Django 4.1.6 on 2023-04-18 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0042_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='card_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
