# Generated by Django 4.1.6 on 2023-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0043_alter_card_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/cardimages/'),
        ),
    ]
