# Generated by Django 4.1.7 on 2023-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_zoom_level_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://api.dicebear.com/5.x/initials/svg?seed=<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zoom_level',
            field=models.CharField(blank=True, default=0, max_length=1),
        ),
    ]
