# Generated by Django 4.1.6 on 2023-05-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_avatar_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
    ]
