# Generated by Django 4.1.6 on 2023-04-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_customuser_avatar_url 2'),
        ('users', '0033_alter_customuser_avatar_url 2'),
        ('users', '0034_alter_customuser_avatar_url 2'),
        ('users', '0045_alter_customuser_avatar_url'),
    ]

    operations = [
    ]
