# Generated by Django 4.1.6 on 2023-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_remove_customuser_avatar_customuser_avatar_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar_image',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://api.dicebear.com/5.x/pixel-art/svg?seed=784', max_length=500),
        ),
    ]
