# Generated by Django 4.1.6 on 2023-04-18 16:06

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_rename_avatar_image_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar1',
            field=models.FileField(blank=True, default=pathlib.PurePosixPath('/Users/peter/Documents/Projecten/kaartenmaker.nl/src/staticfiles/images/avatar.jpg'), null=True, upload_to='media/avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://api.dicebear.com/5.x/pixel-art/svg?seed=985', max_length=500),
        ),
    ]
