# Generated by Django 4.1.6 on 2023-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_remove_customuser_avatar_customuser_avatar1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avatar1',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://api.dicebear.com/5.x/pixel-art/svg?seed=766', max_length=500),
        ),
    ]
