# Generated by Django 4.1.6 on 2023-02-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0004_alter_card_author_alter_card_followers_and_more'),
        ('card_interactions', '0003_remove_like_author_like_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('document_description', models.TextField()),
                ('document_type', models.CharField(choices=[('link', 'Link'), ('document', 'Document')], max_length=20)),
                ('document_url', models.CharField(max_length=500)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_card', to='workshop.card')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
