# Generated by Django 4.1.6 on 2023-02-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_interactions', '0005_rename_documents_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(blank=True),
        ),
    ]
