# Generated by Django 4.1.7 on 2023-04-28 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('contacted_lead', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('internalnotes', models.TextField()),
                ('description', models.TextField()),
                ('contacted_lead', models.BooleanField(default=False)),
            ],
        ),
    ]
