# Generated by Django 4.1.7 on 2023-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_emaillist_contacted_lead_emaillist_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='contacted_lead',
            field=models.BooleanField(default=False),
        ),
    ]
