# Generated by Django 4.1.6 on 2023-04-04 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_emaillist_contacted_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('internalnotes', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
