# Generated by Django 4.1.6 on 2023-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contacted_lead',
            field=models.BooleanField(default=False),
        ),
    ]
