# Generated by Django 4.1.6 on 2023-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_preferredname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
