name: 🚨 Lighthouse Test

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Triagedeploy"]
    types:
      - completed

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://triage.mapmaker.nl/
            https://triage.mapmaker.nl/blog
            https://triage.mapmaker.nl/contact
            https://triage.mapmaker.nl/login
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage