name: 🧪 Tests
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - '**'        # matches every branch
permissions:
  contents: read

env:
  AWS_REGION: eu-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: mapmaker
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  testsuite:
    name: 🧑🏻‍🔬 running tests
    runs-on: ubuntu-latest
    steps:
      - name: 🗂  Getting code from Github
        uses: actions/checkout@v3
      - name: ⚙️  Updating to the latest versions
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: 🤐 Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER_GMAIL }}
          envkey_EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD_GMAIL }}
          envkey_DJANGO_SECRET_KEY: teststring
          envkey_DB_USER: ${{ secrets.DATABASE_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DB_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DB_NAME: "mapmaker_dev"
          envkey_HCTI_API_KEY: ${{ secrets.HCTI_API_KEY }}
          envkey_HCTI_API_USER_ID: ${{ secrets.HCTI_API_USER_ID }}
          envkey_MYSQL_ATTR_SSL_CA: ${{ secrets.MYSQL_ATTR_SSL_CA }}
          envkey_SECURE_SETTINGS: True
          envkey_DEBUG: True
          envkey_MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN}}
          envkey_S3_AWS_STORAGE_BUCKET_NAME: ${{ secrets.S3_AWS_STORAGE_BUCKET_NAME}}
          envkey_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
          envkey_S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY}}
          directory: src/core
          file_name: .env
          fail_on_empty: false
      - name: Installing dependancies
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install -r Infrastructure/requirements.txt
      - name: 🤷🏻‍♂️ Running tests
        run: |
          cd src
          python3 manage.py test --noinput
